PACKAGE_NAME="dnfs"
PACKAGE_VERSION="0.1.0"
PRE_BUILD="ln -sf ${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/fs/nfs/nfs_multipath.h /lib/modules/${kernelver}/build/include/linux/nfs_multipath.h 2>/dev/null; true"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/fs/nfs modules"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/fs/nfs clean"
BUILT_MODULE_NAME[0]="nfs"
BUILT_MODULE_LOCATION[0]="fs/nfs/"
DEST_MODULE_LOCATION[0]="/updates/dnfs"
BUILT_MODULE_NAME[1]="nfsv4"
BUILT_MODULE_LOCATION[1]="fs/nfs/"
DEST_MODULE_LOCATION[1]="/updates/dnfs"
BUILT_MODULE_NAME[2]="nfsv3"
BUILT_MODULE_LOCATION[2]="fs/nfs/"
DEST_MODULE_LOCATION[2]="/updates/dnfs"
AUTOINSTALL="yes"
REMAKE_INITRD="no"
