PACKAGE_NAME="dnfs"
PACKAGE_VERSION="0.1.0"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/fs/nfs modules"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/fs/nfs clean"
BUILT_MODULE_NAME[0]="nfs"
BUILT_MODULE_LOCATION[0]="fs/nfs/"
DEST_MODULE_LOCATION[0]="/updates/dnfs"
BUILT_MODULE_NAME[1]="nfsv4"
BUILT_MODULE_LOCATION[1]="fs/nfs/"
DEST_MODULE_LOCATION[1]="/updates/dnfs"
AUTOINSTALL="yes"
REMAKE_INITRD="no"
