- hosts: dcache
  gather_facts: yes
  tags: [always]
  tasks:
    - name: Show target info
      debug:
        msg: "Deploying dnfs multipath to {{ inventory_hostname }} ({{ server_ip_a }}, {{ server_ip_b }})"

- hosts: dcache
  gather_facts: no
  tags: [network]
  roles:
    - role: network

- hosts: dcache
  gather_facts: no
  tags: [kernel]
  roles:
    - role: kernel

- hosts: dcache
  gather_facts: no
  tags: [mount, nfs]
  roles:
    - role: nfs-mount
